---
zcash_swapfile_size: 1G
zcash_vm_swappiness: 1
zcash_common_packages:
  - apt-show-versions
  - apt-transport-https
  - curl
  - git-core
  - haveged
  - htop
  - ntp
  - ntpdate
  - python-pip
  - rsync
  - screen
  - sudo
  - tmux
  - tree
  - vim
