---
- name: Copy unattended-upgrades configuration.
  copy:
    dest: /etc/apt/apt.conf.d/
    src: "{{ item }}"
    mode: "0640"
    owner: root
    group: root
  with_items:
    - 02periodic
    - 50unattended-upgrades

- name: Enable automatic updates in unattended-upgrades package config.
  shell: echo unattended-upgrades unattended-upgrades/enable_auto_updates boolean true | debconf-set-selections
